WebStore/WEB/src/java/model/Cart.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author admin
 */
public class Cart {
private List<Item> items;
public Cart(){
    items = new ArrayList<>();
}

public List<Item> getItems(){
    return items;
}

public int getQuantityById(int id){
    return getItemByID(id).getQuantity();
}

private Item getItemByID(int id){
    for(Item i : items){
        if(i.getProduct().getId()==id){
            return i;
        }
    }
    
    return null;
}

public void addItem(Item t){
    if(getItemByID(t.getProduct().getId())!= null){
        Item m = getItemByID(t.getProduct().getId());
            m.setQuantity(m.getQuantity()+t.getQuantity());
    }else{
        items.add(t);
    }
}

public void removeItem(int id){
    if(getItemByID(id)!=null){
        items.remove(getItemByID(id));
    }
}

public double getTotalMoney(){
    double t = 0;
    for (Item i : items) {
        t+=(i.getQuantity()*i.getProduct().getPrice());
    }
    return t;
}

private Product getProductbyID(int id, List<Product> list){
    for (Product i : list) {
        if(i.getId()==id){
            return i;
        }
    }
    
    return null;
}
public Cart(String txt,List<Product> list){
    items = new ArrayList<>();
    try{
    if(txt!=null && txt.length()!=0){
        String[] s = txt.split("/");
        for (String i : s) {
            String[] n = i.split(":");
            int id= Integer.parseInt(n[0]);
            int quantity=Integer.parseInt(n[1]);
            Product p = getProductbyID(id, list);
            Item t = new Item(p, quantity, p.getPrice());
            addItem(t);
        }
    }
    }catch(NumberFormatException e){
        
    }
}
    
    
    
}

WebStore/WEB/src/java/model/Product.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.sql.Date;

/**
 *
 * @author admin
 */
public class Product {

    private int id;
    private String name;
    private int quantity;
    private double price;
    private Date releaseDate;
    private String describe, image;
    private Category cid;


    

    
    
    public Product() {
    }

    public Product(int id, String name, int quantity, double price, Date releaseDate, String describe, String image, Category cid) {
        this.id = id;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
        this.releaseDate = releaseDate;
        this.describe = describe;
        this.image = image;
        this.cid = cid;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Date getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Category getCid() {
        return cid;
    }

    public void setCid(Category cid) {
        this.cid = cid;
    }

}

WebStore/WEB/src/java/Controller/AddAccountServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package Controller;

import dal.DAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import model.Account;

/**
 *
 * @author admin
 */
@WebServlet(name="AddAccountServlet", urlPatterns={"/addaccount"})
public class AddAccountServlet extends HttpServlet {
   
    /** 
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet AddAccountServlet</title>");  
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet AddAccountServlet at " + request.getContextPath () + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    } 

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /** 
     * Handles the HTTP <code>GET</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
           request.getRequestDispatcher("addaccount.jsp").forward(request, response);
    } 

    /** 
     * Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
                request.setCharacterEncoding("UTF-8");
        String name = request.getParameter("user");
        String pass = request.getParameter("password");
        String passwordagain = request.getParameter("passwordagain");
        String address = request.getParameter("address");
        String phone = request.getParameter("phone");
        DAO dao = new DAO();
        try {
            if (!pass.equals(passwordagain)) {
                request.setAttribute("error1", "Password and Confirm Password is not equal!!!!");
                request.getRequestDispatcher("addaccount.jsp").forward(request, response);
            } else {
                Account c = dao.getAccountsByUser(name);
                if (c == null) {
                    Account cNew = new Account(name, pass, address, phone, 1);
                    dao.insertAccount(cNew);
                    response.sendRedirect("crudaccount");
                } else {
                    request.setAttribute("error12", name + " existed!!!!");
                    request.getRequestDispatcher("addaccount.jsp").forward(request, response);
                }
            }

        } catch (NumberFormatException e) {
            System.out.println(e);
        }
    }

    /** 
     * Returns a short description of the servlet.
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

WebStore/WEB/src/java/Controller/AddCategoryServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package Controller;

import dal.DAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.sql.Date;
import model.Category;
import model.Product;

/**
 *
 * @author admin
 */
@WebServlet(name="AddCategoryServlet", urlPatterns={"/addcategory"})
public class AddCategoryServlet extends HttpServlet {
   
    /** 
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet AddCategoryServlet</title>");  
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet AddCategoryServlet at " + request.getContextPath () + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    } 

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /** 
     * Handles the HTTP <code>GET</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
              request.getRequestDispatcher("addcategory.jsp").forward(request, response);
    } 

    /** 
     * Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
                String id_raw = request.getParameter("id");
        String name = request.getParameter("name");
        int id;

        try {
            DAO d = new DAO();
            id = Integer.parseInt(id_raw);
            Category c1 = d.getCategoryById(id);
            if (c1 != null) {
                request.setAttribute("error", "Id " + id + " existed!");
                request.getRequestDispatcher("addcategory.jsp").forward(request, response);
            } else {
                Category c = new Category(id, name);
                d.insertCategory(c);
                response.sendRedirect("crudcategory");
            }
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
    }

    /** 
     * Returns a short description of the servlet.
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

WebStore/WEB/src/java/Controller/AddProductServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package Controller;

import dal.DAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.sql.Date;
import model.Category;
import model.Product;

/**
 *
 * @author admin
 */
@WebServlet(name = "AddProductServlet", urlPatterns = {"/addproduct"})
public class AddProductServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet AddProductServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet AddProductServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.getRequestDispatcher("addproduct.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String id_raw = request.getParameter("id");
        String name = request.getParameter("name");
        String quantity_raw = request.getParameter("quantity");
        String price_raw = request.getParameter("price");
        String date_raw = request.getParameter("releasedate");
        String image_raw = request.getParameter("image");
        System.out.println(image_raw);
        String desc = request.getParameter("describe");
        String cid_raw = request.getParameter("cid");
        int quantity, id;
        double price;
        String image;
        Date date;
        int cid;
        try {
            quantity = Integer.parseInt(quantity_raw);
            price = Double.parseDouble(price_raw);
            image = "img/" + image_raw;
            System.out.println(image);
            date = Date.valueOf(date_raw);
            System.out.println(date);
            cid = Integer.parseInt(cid_raw);
            DAO d = new DAO();
            id = Integer.parseInt(id_raw);
            Product p1 = d.getProductsById1(id);
            if (p1 != null) {
                request.setAttribute("error", "Id " + id + " existed!");
                request.getRequestDispatcher("addproduct.jsp").forward(request, response);
            } else {
                Product p = new Product(id, name, quantity, price, date,
                        desc, image, new Category(cid, ""));
                d.insertProduct(p);
                response.sendRedirect("crud");
            }
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

WebStore/WEB/web/addaccount.jsp
<%-- 
    Document   : addaccount
    Created on : Mar 13, 2024, 8:03:07 PM
    Author     : admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="assets/css/login.css"/>
        <link rel="stylesheet" href="assets/css/bootstrap.min.css"/>
        <title>Add Account</title>
    </head>
    <body>
        <section style="background-color: #eee;">
            <div class="container py-5">
                <div class="row d-flex justify-content-center align-items-center">
                    <div class="col-xl-10 justify-content-center">
                        <div class="card rounded-3 text-black">
                            <div class="row" style="justify-content: center" >
                                <div >
                                    <div class="card-body" style="width: 350px;height: 900px">

                                        <div class="text-center">
                                            <img src="img/logo.png"
                                                 style="width: 185px;" alt="logo">
                                            <h4 class="mt-1 mb-5 pb-1">LTK's Store</h4>
                                        </div>
                                        <p style="color: red;text-align: center">${requestScope.error12}</p>
                                        <p style="color: red;text-align: center">${requestScope.error1}</p>
                                        <form action="addaccount" method="post" >
                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example11">Username</label>
                                                <input type="text" id="form2Example11" class="form-control"
                                                       placeholder="Phone number or address" name="user" required/>

                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example22">Password</label>
                                                <input type="password" id="form2Example22" class="form-control" name="password" required />

                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example22">Confirm Password</label>
                                                <input type="password" id="form2Example22" class="form-control" name="passwordagain" required />

                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example22">Address</label>
                                                <input type="text " id="form2Example22" class="form-control" name="address" required />

                                            </div>
                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example22">Phone</label>
                                                <input type="number" id="form2Example22" class="form-control" name="phone" required />

                                            </div>

                                            <div class="text-center pt-1 mb-5 pb-1">
                                                <input class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit" value="Add"/>
                                            </div>

                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

WebStore/WEB/web/addcategory.jsp
<%-- 
    Document   : addcategory
    Created on : Mar 14, 2024, 11:01:56 AM
    Author     : admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
        <link rel="stylesheet" href="assets/css/login.css"/>
        <link rel="stylesheet" href="assets/css/bootstrap.min.css"/>
        <title>Add Category</title>
    </head>
    <body>
        <section style="background-color: #eee;">
            <div class="container py-5">
                <div class="row d-flex justify-content-center align-items-center">
                    <div class="col-xl-10 justify-content-center">
                        <div class="card rounded-3 text-black">
                            <div class="row" style="justify-content: center" >
                                <div >
                                    <div class="card-body" style="width: 350px;height: 1100px">

                                        <div class="text-center">
                                            <img src="img/logo.png"
                                                 style="width: 185px;" alt="logo">
                                            <h4 class="mt-1 mb-5 pb-1">LTK's Store</h4>
                                        </div>
                                        <h5 style="color: red; text-align: center">${requestScope.error}</h5>
                                        <jsp:useBean id="cat" class="dal.DAO"/>
                                        <form action="addcategory" method="post">
                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example11">ID</label>
                                                <input type="number" id="form2Example11" class="form-control" name="id" required/>

                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example22">Name Category</label>
                                                <input type="text" id="form2Example22" class="form-control" name="name" required />

                                            </div>


                                            <div class="text-center pt-1 mb-5 pb-1">
                                                <input class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit" value="Add"/>
                                            </div>

                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

WebStore/WEB/web/changepass.jsp
<%-- 
    Document   : changpass
    Created on : Mar 19, 2024, 1:19:52 PM
    Author     : admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="./assets/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="assets/css/home.css"/>
        <title>JSP Page</title>
    </head>
    <body>
        <section style="background-color: #eee;">
            <div class="container py-5">
                <div class="row d-flex justify-content-center align-items-center">
                    <div class="col-xl-10 justify-content-center">
                        <div class="card rounded-3 text-black">
                            <div class="row" style="justify-content: center" >
                                <div >
                                    <div class="card-body" style="width: 350px;height: 1100px">

                                        <div class="text-center">
                                            <img src="img/logo.png"
                                                 style="width: 185px;" alt="logo">
                                            <h4 class="mt-1 mb-5 pb-1">LTK's Store</h4>
                                        </div>
                                        <h5 style="color: red;margin-left: -40px; width: 500px">${requestScope.mess}</h5>
                                        <c:set var="acc" value="${sessionScope.acc}"/>
                                        <form action="changepass" method="post" >
                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example11">Username</label>
                                                <input type="text" id="form2Example11" class="form-control"
                                                       name="user" value="${acc.user}" readonly/>

                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example22">Old Password</label>
                                                <input type="text" id="form2Example22" class="form-control" name="oldpass" value="${acc.pass}" readonly/>

                                            </div>
                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example22">New Password</label>
                                                <input type="password" id="form2Example22" class="form-control" name="newpass" required/>

                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example22">Confirm Password</label>
                                                <input type="password" id="form2Example22" class="form-control" name="confirmpass" required />

                                            </div>


                                            <div class="text-center pt-1 mb-5 pb-1">
                                                <input class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit" value="Update"/>
                                            </div>


                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

WebStore/WEB/web/mycart.jsp
<%-- 
    Document   : mycart
    Created on : Feb 28, 2024, 1:35:55 PM
    Author     : admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <style>
            table{
                border-collapse: collapse;
            }
            .tr{
                text-align: right;

            }
            a{
                text-decoration: none;
                color: chocolate;
                font-size: 22px;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <h1>Shopping cart online</h1>
        <table border="1px" width="40%">
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Totol money</th>
                <th>Action</th>
                
            </tr>
            <c:set var="o" value="${requestScope.cart}"/>
            <c:set var="tt" value="0"/>
            <c:forEach items="${o.getItems()}" var="i">
                <c:set var="tt" value="${tt+1}"/>
                <tr>
                    <td>${tt}</td>
                    <td>${i.product.name}</td>
                    <td style="text-align: center">
                        <button><a href="process?num=-1&id=${i.product.id}">-</a></button>
                        ${i.quantity}
                        <button><a href="process?num=1&id=${i.product.id}">+</a></button>
                    </td>
                    <td class="tr" >
                        $<fmt:formatNumber pattern="##.#" value="${i.price}"/>
                    </td>
                    <td class="tr">
                         $<fmt:formatNumber pattern="##.#" value="${(i.price*i.quantity)}"/>
                    </td>
                    <td style="text-align: center">
                        <form action="process" method="post">
                            <input type="hidden" name="id" value="${i.product.id}" />
                            <input type="submit" value="return item"/>
                            
                        </form>
                    </td>
                </tr>
            </c:forEach>
        </table>
            <h3>Total money: $ ${o.totalMoney}</h3>
            <hr/>
            <form action="checkout" method="post">
                <input type="submit" value="Check out"/>
            </form>
            <hr/>
            <a href="home">
                Click Me To Continue Shopping
            </a>
    </body>
</html>